# Eureka Server Port
server.port=8761

# Application name
spring.application.name=eureka-server

# Eureka server config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: hostname for dashboard
eureka.instance.hostname=localhost
